# Metadata

```
Course:   DS 5100
Module:   M05 NumPy
Topic:    NumPy First Steps
Author:   R.C. Alvarado (adapted)
Date:     26 June 2022 (revised 13 September 2022)
```

# NumPy

**A new data structure**

Essentially, NumPy introduces a new data structure to Python -- the **n-dimensional array**. Along with it, it introduces a collection of function and methods that take advantage of this data structure.

The data structure is designed to support the use of **numerical methods**: algorithmic approximations to the problems of mathematical analysis.

**New Functions**

It also provides a new way of appling functions to day made possible by the data structure -- **vectorized functions**. Vectorized functions replace the use of loops and comprehensions to apply a function to a set of data. 

In addition, given the data structure, it provides a library of **linear algebra** functions. 

**New Data Types**

NumPy also introduces a bunch of new **data types**.

**Python for Science**

Finally, because [numerical methods](https://www.britannica.com/science/numerical-analysis) are so important to so many sciences, NumPy is the basis of what is called **the scientific "stack"** in Python, which consists of SciPy, Matplotlib, SciKitLearn, and Pandas. All of these assume that you have some knowledge of NumPy.

Let's take a look at it.

In [1]:
import numpy as np

NumPy is by widespread convention aliased as `np`.

# The ndarray

The ndarray is a multidimensional array object.

Let's explore it some. 

First, let's generate some fake data using NumPy's built-a random number generator.

In [2]:
data = np.random.randn(2, 3)

In [3]:
data

array([[-0.38644818, -0.86647565, -1.28487769],
       [-0.34157097,  0.15993769, -1.02030098]])

In [4]:
data * 10

array([[ -3.86448179,  -8.66475646, -12.84877686],
       [ -3.41570969,   1.5993769 , -10.20300981]])

In [5]:
data + data

array([[-0.77289636, -1.73295129, -2.56975537],
       [-0.68314194,  0.31987538, -2.04060196]])

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## About Dimensions

The term dimension is ambiguous.
* Sometimes refers to the dimensions of things in the world, such as space and time.
* Sometimes refers to the dimensions of a data structure, independent of what it represents in the world.

NumPy dimensions are the latter, although they can be used to represent the former, as physicists do.

The dimensions of data structures are sometimes called **axes**.

Consider this: Three-dimensional space can be represented as three columns in a two-dimensional table OR as three axes in a data cube. 


# Creating ndarrays

In [8]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 2.96439388e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.16095484e-028]],

       [[1.14568603e+243, 5.53289000e-048],
        [8.93168689e+271, 4.98131536e+151],
        [1.94920670e-153, 4.05411346e-317]]])

In [17]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Data Types for ndarrays

**Unlike any of the previous data structures we have seen in Python, ndarrays must have a single data type associated with them.**

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [19]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [21]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [22]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [23]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

**NumPy Data Types**

```
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
```

## Arithmetic

In [49]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr.shape

(2, 3)

In [28]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

# Basic Indexing and Slicing

In [57]:
foo = np.zeros((4,6))
foo.shape
foo[2:,:1].shape

(2, 1)

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

In [37]:
arr[5:8] = 12

In [38]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Notice that if we assign a scalar to a slice, all of the elements of the slice get that value. This is called **broadcasting**.

Also, notice that changes to slices are changes to the arrays they are slices of. They are **views**, not copies. 

In [39]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [40]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [41]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [42]:
arr_slice

array([64, 64, 64])

As NumPy has been designed with large data use cases in mind, you could imagine performance and memory problems if NumPy insisted on copying data left and right.

⭐ If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array; for example `arr[5:8].copy()`.

**Higher Dimensional Arrays**

In [43]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [44]:
arr2d[2]

array([7, 8, 9])

In [45]:
arr2d[0][2]

3

**Simplified notation**

In [46]:
arr2d[0, 2]

3

A nice visual of a 2D array

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172112.png" height="50%" width="50%"/>

**Two-Demensional Array Slicing**

<img src="https://learning.oreilly.com/api/v2/epubs/urn:orm:book:9781449323592/files/httpatomoreillycomsourceoreillyimages2172114.png" height="50%" width="50%"/>

**3D arrays**

In [47]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [48]:
arr3d.shape

(2, 2, 3)

In [49]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

If find NumPy's way of show the data a bit difficult to parse visually.

💡 **Here is a way to visualize 3 and higher dimensional data:**

```python
[ # AXIS 0                     CONTAINS 2 ELEMENTS (arrays)
    [ # AXIS 1                 CONTAINS 2 ELEMENTS (arrays)
        [1, 2, 3], # AXIS 3    CONTAINS 3 ELEMENTS (integers)
        [4, 5, 6]  # AXIS 3
    ],  
    [ # AXIS 1
        [7, 8, 9], 
        [10, 11, 12]
    ]
]
```
Each axis is a level in the nested hierarchy, i.e. a tree or DAG (directed-acyclic graph).

* Each axis is a container.
* There is only one top container.
* Only the bottom containers have data.

**Omit lower indices**

In multidimensional arrays, if you omit later indices, the returned object will be a **lower-dimensional ndarray** consisting of all the data contained by the higher indexed dimension. 

So in the 2 × 2 × 3 array `arr3d`:

In [50]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Saving data before modifying an array.

In [51]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Putting the data back.

In [52]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly, `arr3d[1, 0]` gives you all of the values whose indices start with (1, 0), forming a 1-dimensional array:

In [53]:
arr3d[1, 0]

array([7, 8, 9])

In [54]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [55]:
x[0]

array([7, 8, 9])

## Indexing with slices

In [56]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [57]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [58]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [61]:
arr2d[1, :2]

array([4, 5])

In [62]:
arr2d[:2, 2]

array([3, 6])

In [63]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [64]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

This a crucial topic -- it applies to Pandas and R. 

You can pass a boolean representation of an array to the array indexer (i.e. `[]`) and it will return only those cells that are `True`.

This is like replace `IF` statements with a `dict`.

Let's assume that we have two related arrays:
* `names` which is the rows (observations) of a table
* `data` which holds the data associated with each feature

There are $7$ observations and $4$ features.

In [65]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [66]:
data = np.random.randn(7, 4)
data

array([[ 0.72645805, -0.56018644, -0.02850689, -0.34258849],
       [ 0.08356218,  1.55733948, -0.05742818,  0.22044621],
       [ 0.4855556 ,  0.62554909,  1.53878618,  0.79301804],
       [-0.25832437,  0.08506926, -0.28992256, -0.94928641],
       [ 0.2242655 ,  0.32470258,  0.59138963,  0.46460051],
       [ 2.44728205, -1.72271191,  1.1130361 , -1.29616365],
       [-2.43837713, -0.63412397, -0.32796264, -0.68093127]])

In [67]:
names.shape, data.shape

((7,), (7, 4))

A comparison operation in an array returns an array of booleans.

In [68]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

This array can be passed to an array indexer:

In [69]:
data[names == 'Bob']

array([[ 0.72645805, -0.56018644, -0.02850689, -0.34258849],
       [-0.25832437,  0.08506926, -0.28992256, -0.94928641]])

Along the second axis, we can use a slice to select data.

In [70]:
data[names == 'Bob', 2:]

array([[-0.02850689, -0.34258849],
       [-0.28992256, -0.94928641]])

In [71]:
data[names == 'Bob', 3]

array([-0.34258849, -0.94928641])

If you know SQL, this is like the query:

```sql
SELECT col3, col4 FROM data WHERE name = 'Bob'
```

Here are some examples of boolean operations being applied.

Note that we don't use `not` but instead the tilde `~` sign to negate (flip) a value.

In [72]:
names != 'Bob'
data[~(names == 'Bob')]

array([[ 0.08356218,  1.55733948, -0.05742818,  0.22044621],
       [ 0.4855556 ,  0.62554909,  1.53878618,  0.79301804],
       [ 0.2242655 ,  0.32470258,  0.59138963,  0.46460051],
       [ 2.44728205, -1.72271191,  1.1130361 , -1.29616365],
       [-2.43837713, -0.63412397, -0.32796264, -0.68093127]])

In [73]:
cond = names == 'Bob'
data[~cond]

array([[ 0.08356218,  1.55733948, -0.05742818,  0.22044621],
       [ 0.4855556 ,  0.62554909,  1.53878618,  0.79301804],
       [ 0.2242655 ,  0.32470258,  0.59138963,  0.46460051],
       [ 2.44728205, -1.72271191,  1.1130361 , -1.29616365],
       [-2.43837713, -0.63412397, -0.32796264, -0.68093127]])

Similarly, we don't use `and` and `or` but `&` and `|`.

Also, expressions join by these operators need to be in parentheses.

In [74]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[ 0.72645805, -0.56018644, -0.02850689, -0.34258849],
       [ 0.4855556 ,  0.62554909,  1.53878618,  0.79301804],
       [-0.25832437,  0.08506926, -0.28992256, -0.94928641],
       [ 0.2242655 ,  0.32470258,  0.59138963,  0.46460051]])

In [75]:
data[data < 0] = 0
data

array([[0.72645805, 0.        , 0.        , 0.        ],
       [0.08356218, 1.55733948, 0.        , 0.22044621],
       [0.4855556 , 0.62554909, 1.53878618, 0.79301804],
       [0.        , 0.08506926, 0.        , 0.        ],
       [0.2242655 , 0.32470258, 0.59138963, 0.46460051],
       [2.44728205, 0.        , 1.1130361 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [76]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.08356218, 1.55733948, 0.        , 0.22044621],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [2.44728205, 0.        , 1.1130361 , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

## Fancy Indexing

In so-call fancy indexing, we use array index numbers to access data.

We pass a `list` of item numbers, instead of an integer or integer range with `:`, to the indexer.

In [77]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

This says: _Select rows 4, 3, 0, and 6, in that order._

In [78]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

And we can go backwards.

In [79]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [80]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

We can drop these lists into each axis seletor.

In [81]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [82]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping which similarly returns a view on the underlying data without copying anything. 

Arrays have the transpose method and also the special `T` attribute:

In [83]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [84]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Transposing is often used when computing the dot product between two arrays.

Here's an example.

In [85]:
arr = np.random.randn(6, 3)
arr

array([[ 1.01446309, -0.33476867, -0.09004033],
       [ 1.85970397,  0.4631975 , -0.90913396],
       [-1.24259192,  0.95845034,  0.82966335],
       [ 0.26960182,  1.06311444,  1.94385399],
       [-1.73481184, -1.81155925, -2.62414992],
       [ 0.34698368,  2.53034496,  0.76947292]])

In [86]:
np.dot(arr.T, arr)

array([[ 9.23432379,  3.63815754,  2.53047186],
       [ 3.63815754, 12.05985389,  9.17159944],
       [ 2.53047186,  9.17159944, 12.77979278]])

For higher dimensional arrays, `transpose` will accept a tuple of axis numbers to permute the axes.

Warning -- this can get confusing to conceptualize and visualize!

In [87]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [88]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Simple transposing with `.T` is just a special case of swapping axes. ndarray has the method `swapaxes` which takes a pair of axis numbers:

In [89]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [90]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

# Universal Functions

A universal function, or `ufunc`, is a function that performs elementwise operations on data in ndarrays. You can think of them as **fast vectorized wrappers for simple functions** that take one or more scalar values and produce one or more scalar results.

Many `ufuncs` are simple elementwise transformations, like `sqrt` or `exp`:

In [91]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [94]:
x = np.random.randn(8)
x

array([ 2.02607437, -1.26447095, -0.60149557, -0.25198465,  1.04115859,
        2.82900758,  0.76335636,  1.43884518])

In [95]:
y = np.random.randn(8)
y

array([-0.1390021 ,  0.22630824,  0.03067293,  0.68678514, -0.95402859,
        0.91490042, -0.89161303, -0.21106389])

In [96]:
np.maximum(x, y)

array([2.02607437, 0.22630824, 0.03067293, 0.68678514, 1.04115859,
       2.82900758, 0.76335636, 1.43884518])

In [97]:
arr = np.random.randn(7) * 5
arr

array([-7.62726057,  0.68306069, -7.20196344,  9.64982146,  3.74868847,
       -5.69689758,  2.8396405 ])

In [98]:
remainder, whole_part = np.modf(arr)
remainder

array([-0.62726057,  0.68306069, -0.20196344,  0.64982146,  0.74868847,
       -0.69689758,  0.8396405 ])

In [99]:
whole_part

array([-7.,  0., -7.,  9.,  3., -5.,  2.])

In [100]:
arr

array([-7.62726057,  0.68306069, -7.20196344,  9.64982146,  3.74868847,
       -5.69689758,  2.8396405 ])

In [101]:
np.sqrt(arr)

/var/folders/14/rnyfspnx2q131jp_752t9fc80000gn/T/ipykernel_7322/2296558006.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan, 0.82647486,        nan, 3.10641618, 1.93615301,
              nan, 1.68512329])

In [102]:
np.sqrt(arr, arr)

/var/folders/14/rnyfspnx2q131jp_752t9fc80000gn/T/ipykernel_7322/269955669.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([       nan, 0.82647486,        nan, 3.10641618, 1.93615301,
              nan, 1.68512329])

In [103]:
arr

array([       nan, 0.82647486,        nan, 3.10641618, 1.93615301,
              nan, 1.68512329])

`nan` is a special value in NumPy.